version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

  ui:
    image: ui
    depends_on:
      - api
    build:
      context: UI
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001

volumes:
  mongo_volume: